repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-illegal-windows-names
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.8.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        args: [--max-line-length=88]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-pyyaml]
        exclude: ^testing/resources/
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
